### PR TITLE
Isolate serialization of python objects in G3PipelineInfo interface

### PR DESCRIPTION
**Pull request by arahlin**
This PR adds logic throughout the G3PipelineInfo and G3ModuleConfig class definitions to enable them to serialize appropriately in a pure-C++ program.  Notably, any serialization of python objects is handled only on interface with the python interpreter, and otherwise stored in C++ memory with the string representation.

### CODE REVIEW

**Comment by cozzyd** [comment]
This looks good to me!

**Comment by nwhitehorn** [comment]
Just so I understand fully from reading the code: every object gets repr() called on it and the repr() of everything is now stored. For frame objects, the frame object is *also* serialized. On deserialization, any frame objects are instantiated, but things where just the repr() is stored are only evaluated lazily. Is that correct?

**Comment by arahlin** [comment]
Yeah that's right.  I'm going to rearrange a bit so that the repr for frame objects in v1 files doesn't need to be grabbed on load, so that we don't need to grab the GIL in C++ only code ever.

**Comment by nwhitehorn** [comment]
That sounds great. I'll hold off formally approving until those commits are in, but this is a *really* nice solution to the problem.

**Comment by arahlin** [comment]
Should be all set now.  Thanks!

**Review by nwhitehorn — APPROVED** [review]
Looks great!

**Pull request merged**
