### PR TITLE
StokesVector and MuellerMatrix Improvements

### PR DESCRIPTION
**Pull request by arahlin**
* Add StokesVector constructor from polarization angle and efficiency
* Add MuellerMatrix constructor from StokesVector components
* Add `MuellerMatrix.from_vector` method for populating an existing MuellerMatrix from a StokesVector
* Add `rotate_pol` methods for both structures (for use eventually in handling boresight rotation)
* Use these features in MapBinner and MapMockObserver

### CODE REVIEW

**Comment by nwhitehorn** [comment]
Why the case change in det() and inv()? Any expected fallout? I don't think those are used much.

**Comment by arahlin** [comment]
> Why the case change in det() and inv()? Any expected fallout? I don't think those are used much.

These are relatively minimal structures, so I thought their methods should be lowercase to indicate that in some way.  Could revert to camel case if you prefer.

These structures are only really used within the maps library AFAIK, so I don't expect any issues with the case change.

**Comment by nwhitehorn** [comment]
If the usage is fully internal, I don't think it matters either way.

**Review by nwhitehorn — APPROVED** [review]
Looks great! This has been needed for a long time.

**Pull request merged**
